config/routes.rb
Recipes::Application.routes.draw do
  devise_for :users,
              :controllers => {
              :sessions => 'my_devise/sessions'
              }

  resources :recipes do
    resources :ingredients
    resources :preperations
  end

  resources :favourites, :create, :destroy

  scope :controller => :mains do
    get "about"
    get "contact_us"

  end

  scope :controller => :recipes do
    get "search"
    get "my_recipes"
    get "all_recipes"
    get "userrecipes"
  end

 match 'search' => 'recipes#search', :via => [:get, :post], :as => :search
 

  authenticated :user do
    root :to => 'recipes#index'
  end

   root :to => 'mains#index'

end

app/controllers/public_pages_controller.rb
class PublicPagesController < ApplicationController

  def index

    @recipes = Recipe.all
    @latestrecipe = Recipe.order("created_at desc").limit(5)
    @featurerecipe = Recipe.offset(rand(Recipe.count)).first
    @toprankingcountry = Recipe.top_countries.first
    
  end
end

app/helpers/public_pages_helper.rb
module PublicPagesHelper
end

app/views/public_pages/index.html.erb
<h1>All Recipes</h1>

<table>
  <tr>
    <th>Name Of Dish</th>
    <th>Country Of Origin</th>
    <th>Difficulty</th>
    <th>Preperation Time</th>
    <th>ingredient</th>
    <th>Preperation</th>
    <th>Delete</th>
    <th>Edit</th>
    <th>New</th>
  </tr>

  <% @recipes.each do |r| %>
  <tr>
    <td><%= r.dish_name %></td>
    <td><% if r.country %><%= r.country.name %></td><% end %>
    <td><%= r.difficulty %></td>
    <td><%= r.preperation_time %></td>
    <td><%= ingredient_names(r.ingredients) %></td>
    <td><%= preperation_steps(r.preperations) %></td>
    
    <td><%= link_to "Delete Recipe", recipe_path(r.id), :confirm => "Are you sure?", :method => :delete %></td>
    <td><%= link_to "Edit Recipe", edit_recipe_path(r.id) %></td>
    <td><%= link_to "New Recipe", new_recipe_path %></td>

 </tr>

  <% end %>
</table>

<h2>Latest Recipes</h2>

<% @latestrecipe.each do |r| %>
<li><%= r.dish_name %></li>
<li><% if r.country %><%= r.country.name %></li><% end %>
<li><%= r.difficulty %></li>
<li><%= r.preperation_time %></li>
<li><%= ingredient_names(r.ingredients) %></li>
<li><%= preperation_steps(r.preperations) %></li>
<% end %> 

<h2>Featured Recipe</h2>
<li><%= @featurerecipe.dish_name %></li>


<!--<h2>Top Ranking Country</h2>
<%= @toprankingcountry.country_name  %>-->