config/routes.rb
Recipes::Application.routes.draw do
  devise_for :users,
              :controllers => {
              :sessions => 'my_devise/sessions'
              }

  resources :recipes do
    resources :ingredients
    resources :preperations
  end

  resources :favourites, :create, :destroy

  scope :controller => :mains do
    get "about"
    get "contact_us"

  end

  scope :controller => :recipes do
    get "search"
    get "my_recipes"
    get "all_recipes"
    get "userrecipes"
  end

 match 'search' => 'recipes#search', :via => [:get, :post], :as => :search
 

  authenticated :user do
    root :to => 'recipes#index'
  end

   root :to => 'mains#index'

end

app/models/country.rb
class Country < ActiveRecord::Base

  has_many :recipes

 

  scope :code, lambda { |code| where(:code => code.to_s) }

  validates :code, :presence => true, :length => { :maximum => 5 }, :uniqueness => true
  validates :name, :presence => true, :length => { :maximum => 100 }

  attr_accessible :code, :name, :iso3, :numeric, :eu, :country_id

  #scope :top_countries, order("country_name DESC")
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe

  attr_accessible :user_id, :recipe_id
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe


  attr_accessible :ingredient_name
end

app/models/preperation.rb
class Preperation < ActiveRecord::Base
  belongs_to :recipe

  attr_accessible :prep_steps
  # attr_accessible :title, :body
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

belongs_to :user
belongs_to :country
has_many :ingredients 
has_many :preperations
has_many :favourites










attr_accessible :dish_name, :difficulty, :preperation_time, :ingredients_attributes, :preperations_attributes, :country_id, :avatar, :category, :description

has_attached_file :avatar, :styles => { :myrecipes => "260x180#", :showrecipe => "600x300#", :medium => "300x300>", :thumb => "100x100>" } 

accepts_nested_attributes_for :ingredients, :preperations

#scope :top_countries, order("country_name DESC")

#Scopes

scope :meat_recipes, where(:category => "meat")
scope :veg_recipes, where(:category => "vegeterian")




def self.dessert_recipes
  self.where(:category => "Desserts")

end


def related_recipes

    # take the recipe's dish name (@recipe.dish_name) and
    # split it at spaces, then wrap each with '%' to create SQL query terms,
    # so "italian pasta" becomes ["%italian%", "%pasta%"]
    terms = dish_name.split(' ').map { |t| "%#{t}%" }

    # create a scope with all recipes except this one
    others = self.class.where('id != ?', id)

    # return all recipes other than this one that contain any of the terms
    # e.g. for the dish "italian pasta", this will become:
    # others.where('dish_name LIKE ? OR dish_name LIKE ?', '%italian%', '%pasta%')
    return others.where(terms.map { 'dish_name LIKE ?' }.join(' OR '), *(terms))
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :recipes
  has_many :favourites, :dependent => :destroy
  has_many :favourites

  
  
  

 
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  

   


end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

  def index

  end

  def create
    @favourite = current_user.favourites.new(recipe_id: params[:recipe_id])
    if @favourite.save
      redirect_to my_recipes_path, :notice => "Recipe added to Favourites"
    end
  end

  def destroy
    @favourite = Favourite.find(params[:id])
    @favourite.destroy 
    redirect_to my_recipes_path, :notice => "Successfully deleted favourite"
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def new
    @ingredient = recipe.find(params[:recipe_id]).ingredients.new
    @recipe_id = params[:recipe_id]

  end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  def index

  end

  def about

  end

  def contact_us

  end
end

app/controllers/public_pages_controller.rb
class PublicPagesController < ApplicationController

  def index

    @recipes = Recipe.all
    @latestrecipe = Recipe.order("created_at desc").limit(5)
    @featurerecipe = Recipe.offset(rand(Recipe.count)).first
    @toprankingcountry = Recipe.top_countries.first
    
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
before_filter :authenticate_user!


  def index
    @q = Recipe.search(params[:q])
    @searchresults = @q.result(:distinct => true)
    #@q.build_condition
    
  end

  def search
   index
   render :partial => 'shared/searchresults'

  end

  def my_recipes
    @recipes = current_user.recipes.paginate(:page => params[:user_recipes_page], :per_page => 4) if current_user.recipes 
    @favourites = current_user.favourites.paginate(:page => params[:favourite_page], :per_page => 4) if current_user.favourites


  end

  
  def all_recipes
    
    @recipes = Recipe.all
    @latestrecipe = Recipe.order("created_at desc").limit(5)
    @featurerecipe = Recipe.offset(rand(Recipe.count)).first
    #@toprankingcountry = Recipe.top_countries.first
    @meats= Recipe.meat_recipes.paginate(:page => params[:meat_recipes], :per_page => 1)
    @vegrecipes = Recipe.veg_recipes.paginate(:page => params[:veg_recipes], :per_page => 1)
    @desserts = Recipe.dessert_recipes.paginate(:page => params[:dessert_recipes], :per_page => 1)

     
  end

  def show
    @recipe = Recipe.find(params[:id])
    @related_recipes = @recipe.related_recipes

  end

  def new 

  @recipe = Recipe.new
  @recipe.ingredients.build
  @recipe.preperations.build


  end

  def create
    @recipe = current_user.recipes.new(params[:recipe])
    if @recipe.save
      redirect_to my_recipes_path, :notice => "Thanks #{current_user.name} Recipe sucessfully created."
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])

  end

  def update
    @recipe = Recipe.find(params[:id])

   if @recipe.update_attributes(params[:recipe])
    redirect_to my_recipes_path, :notice => "Successfully updated recipe"
  else 

    render :action => 'edit'
    
  end
end

  def destroy

    @recipe = Recipe.find(params[:id])
    @recipe.destroy 
    redirect_to my_recipes_path, :notice => "Successfully deleted recipe"
    
     
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_login
    if !current_user
      link_to "Log In", new_user_session_path
    else
      link_to "Logout", destroy_user_session_path, :method => :delete
    end
  end
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/ingredient_helper.rb
module IngredientHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/public_pages_helper.rb
module PublicPagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper

  def ingredient_names(ingredients)
    if ingredients
      ingredient_array = ingredients.map {|ing| ing.ingredient_name}
      ingredient_array.join("\n")
    end
  end

  def ingredient_names_list(ingredients)
  return ''  if !ingredients

  ingredients.map(&:ingredient_name)*'<br/>'
end

  def preperation_steps(preperations)
    if preperations
      preperation_array = preperations.map {|pre| pre.prep_steps}
      preperation_array.join("\n")
   end
  end

  def preperation_steps_list(preperations)
  return ''  if !preperations

  preperations.map(&:prep_steps)*'<li/>'
end

  def country_name(country)
    if country
      country_array = country.map {|c| c.country_name}
      country_array.join("\n")
   end
  end



end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipes</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

   <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">×</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>

</head>
<body>
  <div class="container">
    <div class="row">
      <div class="span12">
        <header>
          <h1>RealRecipes</h1>
        </header>
        </div>
      </div>
    </div>
   <div class="container">
    <div class="row">
      <div class="span12">
        <nav>
          <ul class="navBar">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "My Recipes", my_recipes_path %></li>
            <li><%= link_to "All Recipes", all_recipes_path %></li>
            <li><%= link_to "Search Recipes", search_path %></li>
            <li><%= display_login %></li>
          </ul>


        </nav>
      </div>
    </div>
  </div><!--/container-->

    



<%= yield %>



</body>
</html>

app/views/shared/_form.html.erb
<%= nested_form_for @recipe  do |f| %>

<%= f.label :dish_name, "Dish Name" %>
<%= f.text_field :dish_name, :placeholder => "Enter Dish Name" %>
 


<%= f.label :country_id, "Country Of Origin" %>
<%= f.collection_select(:country_id, Country.all, :id, :name, :prompt => 'Please select country') %>

<%= f.label :category, "Category" %>
<%= f.select :category, [['Meat'], ['Vegeterian'], ['Desserts']], {:include_blank => 'Please Select'} %>


<%= f.label :difficulty, "Difficulty Level" %>
<%= f.select :difficulty, [['Beginner'],['Intermediate'],['Expert']], {:include_blank => 'Please Select'} %>

<%= f.label :preperation_time, "Preperation Time (Mins)" %>
<%= f.select :preperation_time, [['15-30 Mins'],['30-60 Mins'],['60-120 Mins']], {:include_blank => 'Please Select'} %>

<%= f.fields_for :ingredients do |ing| %>
 Ingredient<br>
 <%= ing.text_field :ingredient_name , :placeholder => "Enter Ingredient Here" %><br>
<% end %>
<%= f.link_to_add "Add an Ingredient", :ingredients %><br>

<%= f.fields_for :preperations do |prep| %>
 Preperation Step<br>
 <%= prep.text_field :prep_steps , :placeholder => "Enter step Here" %><br>
<% end %>

<%= f.link_to_add "Add a step", :preperations %><br>

<%= f.label :description, "Description of Recipe" %>
<%= f.text_area :description, :size=> "60x10" %></br>

<%= f.file_field :avatar %><br>

<%= f.submit "Submit Recipe" %>
<% end %>

app/views/shared/_myrecipes.html.erb
 <div class="container">
  <div class="row">
    <div id="userRecipes">
    <%= render partial: 'userrecipes' %>
  </div>
</div><!--/row-->
</div>


  

app/views/shared/_navbar.html.erb
 <div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
       <a class="brand" href="#">RealRecipes</a>

        <!-- Everything you want hidden at 940px or less, place within here -->
       <div class="nav-collapse collapse">
       <ul class="nav">
    <li><a href="/">Home</a></li>
    <li><a href="/about">About RealRecipes</a></li>
    <li><a href="contact_us">Contact Us</a></li>
   </ul>
    <ul class="nav pull-right">
     <li><a href="/users/sign_in">Login</a></li>
    </ul>
       </div>
       
   </div>
 </div>
</div>

app/views/shared/_navbarlogin.html.erb
<div class="container">
<div class="navbar">
 <div class="navbar-inner">
  <a class="brand" href="#">RealRecipes</a>
   <ul class="nav">
    <li><a href="/">Home</a></li>
    <li><a href="/about">About RealRecipes</a></li>
    <li><a href="/my_recipes">My Recipes</a></li>
    <li><a href="/search_recipes">Search Recipes</a></li>
    <li><a href="/all_recipes">All Recipes</a></li>
    <li><a href="contact_us">Contact Us</a></li>
   </ul>
    <ul class="nav pull-right">
     <li><%= link_to('Logout', destroy_user_session_path, confirm: 'Are you sure you want to logout?', :method =>:delete) %></li>
    </ul>
 </div>
</div>
</div>

app/views/shared/_searchrecipes.html.erb
<div class="showContent">

<%= search_form_for @q, :url => search_path, :html => {:method => :post }  do |f| %>
<%= f.label :dish_name_cont, "Enter Dish Name" %>
<%= f.text_field :dish_name_cont %><br>
<%= link_to "Advanced Search", :class => 'reveal' %>
<div class="hideContent">
<%= f.label :country_name_cont, "Choose Country" %>

<%= f.collection_select :country_id_eq, Country.all, :id, :name, multiple: true, :prompt => "Please Select" %>

<%= f.label :difficulty_cont, "Choose Difficulty" %>
<%= f.select :difficulty_eq, options_for_select([['Beginner'],['Intermediate'],['Expert']]),{:prompt => 'Please Select'}%>

<%= f.label :preperation_time_cont, "Choose Preperation Time" %>
<%= f.select :preperation_time_eq, options_for_select([['15..30'],['30..60'],['60..120']]), {:prompt => 'Please Select'}%>

<%= f.submit "Search", :class => "searchbutton" %>
<% end %>
</div><!--/hideContent-->
</div>



 

app/views/shared/_searchresults.html.erb
<table>
  <tr>
    <th>Name Of Dish</th>
    <th>Country Of Origin</th>
    <th>Difficulty</th>
    <th>Preperation Time</th>
    <th>ingredient</th>
    <th>Preperation</th>
  </tr>

  <% @countrysearch.each do |r| %>
  <tr>
    <td><%= r.dish_name %></td>
    <td><%= r.country %></td>
    <td><%= r.difficulty %></td>
    <td><%= r.preperation_time %></td>
    <td><%= ingredient_names(r.ingredients) %></td>
    <td><%= preperation_steps(r.preperations) %></td>
    

 </tr>

  <% end %>
</table>